### PR TITLE
add unarchiver example

### PR DESCRIPTION
**Pull request by jm33-m0**
Hi Matt,

As previously discussed, I am opening a new PR to provide the unarchiver example.

> However, I don't think we should be providing an actual program, just an example in the docs.

Yes this is just an example that can be worked on, I am not aiming to change anything of the library itself. I believe you already agreed with that.

If needed, I can add a link in `README.md` for this example.

### CODE REVIEW

**Comment by mholt** [comment]
Thank you!

I do think it's important that we don't provide a program, but we can put something like this in documentation. Maybe the readme, or the wiki. (Drop `main()`, and the go.mod/sum files.)

And while creating an archive is relatively straightforward (the formats are pretty standard), extracting an archive is not. There are many ways to do it -- like there are many ways to copy a directory of files. How do you handle existing files? What if one file fails to copy? Do you create a new folder or litter the destination? What about file properties and names that aren't supported on the target FS? Do you trust directory traversals (`..`)? Symlinks? Hard links? The list goes on.

For these reasons I am not prone to adding a _particularly_ detailed example. There are too many ways to do it, and people will just ask for more examples to do it their way, some of which are less secure and less portable than others. Some may be very niche. There is no one right way to extact an archive, but almost all the ways are the wrong ways.

We should thus explain clearly that extracting an archive is a very opinionated operation, and is often insecure, thus we are leaving the integration/implementation up to the users.

**Comment by jm33-m0** [comment]
> but we can put something like this in documentation. Maybe the readme, or the wiki. (Drop main(), and the go.mod/sum files.)

I don't see any difference, but if you think it's more appropriate I can do that as well. It's just that the code will seem lengthy if put in the documentation.

I totally understand your point that users should decide how to extract the files, it looks like you intend to implement only the lower level APIs instead of providing another `tar`. However, it will be beneficial if we provide a secure default way of unarchiving, maybe even with a new project that does exactly that?

**Comment by mholt** [comment]
Ohh, actually, a separate project for a command / utility would maybe be great. I know a lot of people want it, but it's just not something I need or have time for right now. Beware that it is fraught with security perils however.

**Comment by jm33-m0** [comment]
Very good. I will be happy to maintain the said project if you decide to open one.

**Comment by mholt** [comment]
Thanks. I don't think I should own the repo though if I won't be maintaining it from the start. Might be confusing. 😅

**Comment by jm33-m0** [comment]
I see, my point is to make it easier for people to use this library, if you intend to make the library lower level we can create a new one dedicated to high level archive operations.

I'm going to create the project later, let's work together in the future.

**Comment by mholt** [comment]
Oh I definitely think we can refer to it from here so people can find it and learn from it. 👍

Thanks again for contributing!

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/arc

Done!

**Comment by mholt** [comment]
Legend! I'll add it to the readme, and hope it gets developed more fully! :100: :tada:

**Pull request closed without merging**
